spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ss?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
    